# Generated by Django 6.0.2 on 2026-02-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_bankaccount_qr_code_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('qr_code', 'QR-код (мБанк)'), ('telegram', 'Написать в Telegram')], default='qr_code', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
