# Generated by Django 6.0.2 on 2026-02-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_toolcategory_alter_order_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToolCategory',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория инструментов', 'verbose_name_plural': 'Категории инструментов'},
        ),
    ]
